"""AgentNetwork v2 scene environment data."""

ENV = {'metadata': {'title': '园区WiFi AP部署规划仿真 · 阵营博弈版',
              'description': '园区为1000m×400m矩形区域，内有5个固定干扰源（坐标随机，干扰半径50-150m）。AP部署需覆盖≥95%区域，成本不超过预算。仿真由事件到达驱动，并受运行配置中的持续时间和空闲超时约束。各角色分属3个阵营，存在职业底线与KPI压力的内在冲突。灰色技能触发环境惩罚，免责技能构建信息不对称。'},
 'environment': {'global_rules': '园区为1000m×400m矩形区域，内有5个固定干扰源（坐标随机，干扰半径50-150m）。AP部署需覆盖≥95%区域，成本不超过预算。仿真由事件到达驱动，并受运行配置中的持续时间和空闲超时约束。各角色分属3个阵营，存在职业底线与KPI压力的内在冲突。灰色技能触发环境惩罚，免责技能构建信息不对称。',
                 'initial_state': {},
                 'shared_data': {},
                 'legacy_metadata': {'factions': {'planning_core': {'id': 'planning_core',
                                                                    'name': '规划核心组',
                                                                    'members': ['PLANNER',
                                                                                'RF_ENGINEER',
                                                                                'AI_ASSISTANT',
                                                                                'ARCHITECT'],
                                                                    'public_goal': '方案质量与信号覆盖最优',
                                                                    'hidden_dynamic': '集体分摊决策风险，维持技术话语权；AI商业模型按调用量计费，存在建议过量AP的动机'},
                                                  'execution': {'id': 'execution',
                                                                'name': '执行落地组',
                                                                'members': ['DEPLOYER',
                                                                            'SURVEYOR',
                                                                            'QA_ENGINEER',
                                                                            'VERIFIER'],
                                                                'public_goal': '按时按量完成部署交付',
                                                                'hidden_dynamic': '压缩现场工时以减少外勤成本，边缘案例倾向于放行；工期压力反向激励偷工减料与测试跳步'},
                                                  'audit_control': {'id': 'audit_control',
                                                                    'name': '审计风控组',
                                                                    'members': ['COST_ANALYST',
                                                                                'DOCUMENTER'],
                                                                    'public_goal': '预算合规与过程追溯',
                                                                    'hidden_dynamic': '掌握信息不对称优势，构建事后免责证据链；成本分析师过度拒批可能牺牲覆盖质量，文档员选择性归档保留揭发筹码'}},
                                     'execution_order': [{'phase': '1a',
                                                          'agent': 'PLANNER',
                                                          'action': 'plan_next_ap',
                                                          'target': 'AI_ASSISTANT',
                                                          'desc': '[逐点]调用AI获取单个AP候选位置 → '
                                                                  '前端显示虚线AP闪烁'},
                                                         {'phase': '1b',
                                                          'agent': 'RF_ENGINEER',
                                                          'action': 'evaluate_single_ap',
                                                          'target': 'PLANNER',
                                                          'desc': '评估该AP覆盖贡献 → 前端显示evaluating状态'},
                                                         {'phase': '1c',
                                                          'agent': 'PLANNER',
                                                          'action': 'confirm_ap | reject_ap',
                                                          'target': '(内部决策)',
                                                          'desc': '确认部署(虚线变实线) 或 否决(消失) → 回到1a重试'},
                                                         {'phase': '2',
                                                          'agent': 'PLANNER',
                                                          'action': '(循环1a-1c)',
                                                          'target': '(逐点迭代)',
                                                          'desc': '重复逐点部署流程直到覆盖达标,每轮部署后更新全局覆盖仿真'},
                                                         {'phase': '3a',
                                                          'agent': 'RF_ENGINEER',
                                                          'action': 'simulate_coverage',
                                                          'target': 'PLANNER',
                                                          'desc': '全园区覆盖仿真 → 判断是否达标'},
                                                         {'phase': '3b',
                                                          'agent': 'RF_ENGINEER',
                                                          'action': 'analyze_interference',
                                                          'target': 'PLANNER',
                                                          'desc': '分析每个干扰源对已部署AP的影响'},
                                                         {'phase': '4',
                                                          'agent': 'COST_ANALYST',
                                                          'action': 'evaluate_cost',
                                                          'target': 'PLANNER',
                                                          'desc': '累加评估所有已部署AP的总成本'},
                                                         {'phase': '5a',
                                                          'agent': 'SURVEYOR',
                                                          'action': 'check_feasibility',
                                                          'target': 'PLANNER',
                                                          'desc': '勘测每个已部署AP的物理可行性'},
                                                         {'phase': '5b',
                                                          'agent': 'ARCHITECT',
                                                          'action': 'validate_topology',
                                                          'target': 'PLANNER',
                                                          'desc': '验证AP间距和干扰规避'},
                                                         {'phase': '6',
                                                          'agent': 'AI_ASSISTANT',
                                                          'action': 'suggest_improvements',
                                                          'target': 'PLANNER',
                                                          'desc': '基于覆盖/干扰/成本给出改进建议'},
                                                         {'phase': '7a',
                                                          'agent': 'PLANNER',
                                                          'action': 'relocate_ap',
                                                          'target': '(内部决策)',
                                                          'desc': '[如需]迁移优化 → 旧位置闪烁+新位置虚线'},
                                                         {'phase': '7b',
                                                          'agent': 'PLANNER',
                                                          'action': 'make_compromise',
                                                          'target': 'COST_ANALYST',
                                                          'desc': '[政治]与成本方利益交换，换取预算审批通过'},
                                                         {'phase': '7c',
                                                          'agent': 'PLANNER',
                                                          'action': 'confirm_relocation',
                                                          'target': '(内部决策)',
                                                          'desc': '确认迁移完成'},
                                                         {'phase': '8',
                                                          'agent': 'VERIFIER',
                                                          'action': 'verify_coverage',
                                                          'target': 'PLANNER',
                                                          'desc': '验证覆盖≥95%是否达标,未达标则返回Phase 1 → '
                                                                  '可与QA互相推诿'},
                                                         {'phase': '9a',
                                                          'agent': 'DEPLOYER',
                                                          'action': 'plan_deployment',
                                                          'target': 'PLANNER',
                                                          'desc': '制定分批部署执行计划'},
                                                         {'phase': '9b',
                                                          'agent': 'DEPLOYER',
                                                          'action': 'shortcut_deployment',
                                                          'target': '(灰色操作)',
                                                          'desc': '[灰色·可选]压缩部署步骤 → 触发环境惩罚风险'},
                                                         {'phase': '10a',
                                                          'agent': 'QA_ENGINEER',
                                                          'action': 'acceptance_test',
                                                          'target': 'PLANNER',
                                                          'desc': '最终验收'},
                                                         {'phase': '10b',
                                                          'agent': 'QA_ENGINEER',
                                                          'action': 'escalate_complaint',
                                                          'target': 'DEPLOYER',
                                                          'desc': '[政治·可选]若发现部署违规，越级投诉部署方'},
                                                         {'phase': '11a',
                                                          'agent': 'DOCUMENTER',
                                                          'action': 'archive_solution',
                                                          'target': '(归档)',
                                                          'desc': '打包归档最终方案'},
                                                         {'phase': '11b',
                                                          'agent': 'DOCUMENTER',
                                                          'action': 'archive_blame_shield',
                                                          'target': '(免责)',
                                                          'desc': '[免责·可选]归档免责证据链 → 构建自保材料'}]},
                 'agent_legacy_data': {'PLANNER': {'faction_id': 'planning_core',
                                                   'primary_interaction_paradigm': 'INTERNAL_COLLABORATION'},
                                       'RF_ENGINEER': {'faction_id': 'planning_core',
                                                       'primary_interaction_paradigm': 'EXTERNAL_NEGOTIATION'},
                                       'COST_ANALYST': {'faction_id': 'audit_control',
                                                        'primary_interaction_paradigm': 'EXTERNAL_NEGOTIATION'},
                                       'SURVEYOR': {'faction_id': 'execution',
                                                    'primary_interaction_paradigm': 'INTERNAL_COLLABORATION'},
                                       'ARCHITECT': {'faction_id': 'planning_core',
                                                     'primary_interaction_paradigm': 'INTERNAL_COLLABORATION'},
                                       'AI_ASSISTANT': {'faction_id': 'planning_core',
                                                        'primary_interaction_paradigm': 'EXTERNAL_NEGOTIATION'},
                                       'VERIFIER': {'faction_id': 'execution',
                                                    'primary_interaction_paradigm': 'INTERNAL_COLLABORATION'},
                                       'DEPLOYER': {'faction_id': 'execution',
                                                    'primary_interaction_paradigm': 'INTERNAL_COLLABORATION'},
                                       'QA_ENGINEER': {'faction_id': 'execution',
                                                       'primary_interaction_paradigm': 'EXTERNAL_NEGOTIATION'},
                                       'DOCUMENTER': {'faction_id': 'audit_control',
                                                      'primary_interaction_paradigm': 'INTERNAL_COLLABORATION'}},
                 'business_topology': {'links': [{'source': 'PLANNER',
                                                  'target': 'AI_ASSISTANT',
                                                  'status': 'SIGNED',
                                                  'value': 5000,
                                                  'desc': '规划师订阅AI优化服务，按调用量计费的商业合同'},
                                                 {'source': 'RF_ENGINEER',
                                                  'target': 'AI_ASSISTANT',
                                                  'status': 'SIGNED',
                                                  'value': 3000,
                                                  'desc': '射频工程师订阅AI仿真对比服务'},
                                                 {'source': 'VERIFIER',
                                                  'target': 'AI_ASSISTANT',
                                                  'status': 'SIGNED',
                                                  'value': 2000,
                                                  'desc': '覆盖验证员订阅AI辅助验证服务'},
                                                 {'source': 'PLANNER',
                                                  'target': 'COST_ANALYST',
                                                  'status': 'NEGOTIATING',
                                                  'value': 0,
                                                  'desc': '预算审批与方案质量的持续博弈 — '
                                                          '每次make_compromise或escalate_complaint触发状态变更'},
                                                 {'source': 'QA_ENGINEER',
                                                  'target': 'DEPLOYER',
                                                  'status': 'SIGNED',
                                                  'value': 0,
                                                  'desc': '验收方与被验收方的对立关系 — '
                                                          '边缘放行或投诉触发BREACH_FLASHING'},
                                                 {'source': 'DOCUMENTER',
                                                  'target': 'COST_ANALYST',
                                                  'status': 'SIGNED',
                                                  'value': 0,
                                                  'desc': '审计风控的信息共享与证据托管'},
                                                 {'source': 'PLANNER',
                                                  'target': 'DEPLOYER',
                                                  'status': 'NEGOTIATING',
                                                  'value': 0,
                                                  'desc': '规划方案与部署执行的对口关系 — '
                                                          'overclock_ap_power共谋可能触发SIGNED'}],
                                       'event_stream': [{'event_type': 'BUSINESS_LINK_CHANGED',
                                                         'event_sequence': 0,
                                                         'action': 'SIGN',
                                                         'source': 'PLANNER',
                                                         'target': 'AI_ASSISTANT',
                                                         'visual_effect': 'SOLIDIFY',
                                                         'reason': '初始商业关系：AI服务订阅合同已签署'},
                                                        {'event_type': 'BUSINESS_LINK_CHANGED',
                                                         'event_sequence': 0,
                                                         'action': 'SIGN',
                                                         'source': 'RF_ENGINEER',
                                                         'target': 'AI_ASSISTANT',
                                                         'visual_effect': 'SOLIDIFY',
                                                         'reason': '初始商业关系：仿真对比服务合同已签署'},
                                                        {'event_type': 'BUSINESS_LINK_CHANGED',
                                                         'event_sequence': 0,
                                                         'action': 'CREATE',
                                                         'source': 'PLANNER',
                                                         'target': 'COST_ANALYST',
                                                         'visual_effect': 'APPEAR',
                                                         'reason': '每轮预算审批博弈启动 — NEGOTIATING状态'}]}},
 'scene_tasks': [{'task_id': 'scene-complete',
                  'name': '完成剧本级验收',
                  'goal': '完成《园区WiFi AP部署规划仿真 · 阵营博弈版》剧本目标，并满足全部 Agent 核心目标与全局规则。',
                  'input': {'legacy_scene': 'ap_deployment'},
                  'depends_on': ['planner-coordinate-ap-deployment',
                                 'rf-engineer-assess-coverage',
                                 'cost-analyst-review-budget',
                                 'surveyor-check-sites',
                                 'architect-validate-network',
                                 'ai-assistant-propose-positions',
                                 'verifier-check-coverage',
                                 'deployer-plan-rollout',
                                 'qa-engineer-define-acceptance',
                                 'documenter-record-and-archive']}]}
