"""AgentNetwork v2 scene environment data."""

ENV = {'metadata': {'title': '华为范式科技园区仿真',
              'description': '仿真模拟华为科技园区内部跨部门协作与外部资源调用，包括东西向内部流量和南北向外部API调用。所有节点遵守园区网络策略，外部API调用需通过API网关限流。仿真由事件到达驱动，持续时间和空闲终止由本次运行配置决定。'},
 'environment': {'global_rules': '仿真模拟华为科技园区内部跨部门协作与外部资源调用，包括东西向内部流量和南北向外部API调用。所有节点遵守园区网络策略，外部API调用需通过API网关限流。仿真由事件到达驱动，持续时间和空闲终止由本次运行配置决定。',
                 'initial_state': {},
                 'shared_data': {},
                 'agent_legacy_data': {'DEV_FE': {'primary_interaction_paradigm': 'INTERNAL_COLLABORATION'},
                                       'DEV_BE': {'primary_interaction_paradigm': 'INTERNAL_COLLABORATION'},
                                       'DEV_FW': {'primary_interaction_paradigm': 'INTERNAL_COLLABORATION'},
                                       'DEV_AI': {'primary_interaction_paradigm': 'EXTERNAL_NEGOTIATION'},
                                       'DEV_IC': {'primary_interaction_paradigm': 'EXTERNAL_NEGOTIATION'},
                                       'ARCHITECT': {'primary_interaction_paradigm': 'INTERNAL_COLLABORATION'},
                                       'PM': {'primary_interaction_paradigm': 'INTERNAL_COLLABORATION'},
                                       'DOC_WRITER': {'primary_interaction_paradigm': 'INTERNAL_COLLABORATION'},
                                       'QA': {'primary_interaction_paradigm': 'INTERNAL_COLLABORATION'},
                                       'REPO_ADMIN': {'primary_interaction_paradigm': 'INTERNAL_COLLABORATION'},
                                       'DEV_OPS': {'primary_interaction_paradigm': 'INTERNAL_COLLABORATION'}},
                 'business_topology': {'links': [{'source': 'DEV_AI',
                                                  'target': 'EXTERNAL:LLM_INFERENCE',
                                                  'status': 'NEGOTIATING',
                                                  'value': 2000,
                                                  'desc': 'AI训练→LLM推理API(南北向)'},
                                                 {'source': 'DEV_IC',
                                                  'target': 'EXTERNAL:EDA_CLOUD',
                                                  'status': 'NEGOTIATING',
                                                  'value': 5000,
                                                  'desc': 'IC设计→云仿真(南北向)'},
                                                 {'source': 'DEV_BE',
                                                  'target': 'EXTERNAL:CLOUD_BUILD',
                                                  'status': 'NEGOTIATING',
                                                  'value': 500,
                                                  'desc': '后端→Cloud Build API(南北向)'}]}},
 'scene_tasks': [{'task_id': 'scene-complete',
                  'name': '完成剧本级验收',
                  'goal': '完成《华为范式科技园区仿真》剧本目标，并满足全部 Agent 核心目标与全局规则。',
                  'input': {'legacy_scene': 'tech_campus'},
                  'depends_on': ['dev_fe-primary',
                                 'dev_be-primary',
                                 'dev_fw-primary',
                                 'dev_ai-primary',
                                 'dev_ic-primary',
                                 'architect-primary',
                                 'pm-primary',
                                 'doc_writer-primary',
                                 'qa-primary',
                                 'repo_admin-primary',
                                 'dev_ops-primary']}]}
