"""AgentNetwork v2 scene environment data."""

ENV = {'metadata': {'title': '电信运营商招投标竞争与机构合作仿真',
              'description': '本仿真模拟三家电信运营商（移动、联通、电信）与多家机构（政府、金融、教育、医疗、工业）之间的招投标、签约、违约转投等动态合约过程。机构在相关事件到达时评估当前签约运营商的性价比并决定是否转投；运营商可调整报价争夺市场。合约状态包括谈判、签约、违约闪烁、终止。'},
 'environment': {'global_rules': '本仿真模拟三家电信运营商（移动、联通、电信）与多家机构（政府、金融、教育、医疗、工业）之间的招投标、签约、违约转投等动态合约过程。机构在相关事件到达时评估当前签约运营商的性价比并决定是否转投；运营商可调整报价争夺市场。合约状态包括谈判、签约、违约闪烁、终止。',
                 'initial_state': {},
                 'shared_data': {},
                 'agent_legacy_data': {'GOV_AGENCY': {'primary_interaction_paradigm': 'EXTERNAL_NEGOTIATION'},
                                       'FIN_BANK': {'primary_interaction_paradigm': 'ZERO_SUM_GAME'},
                                       'EDU_UNIV': {'primary_interaction_paradigm': 'EXTERNAL_NEGOTIATION'},
                                       'MED_HOSP': {'primary_interaction_paradigm': 'INTERNAL_COLLABORATION'},
                                       'IND_FACTORY': {'primary_interaction_paradigm': 'ZERO_SUM_GAME'},
                                       'OP_MOBILE': {'primary_interaction_paradigm': 'EXTERNAL_NEGOTIATION'},
                                       'OP_UNICOM': {'primary_interaction_paradigm': 'ZERO_SUM_GAME'},
                                       'OP_TELECOM': {'primary_interaction_paradigm': 'EXTERNAL_NEGOTIATION'},
                                       'REGULATOR': {'primary_interaction_paradigm': 'INTERNAL_COLLABORATION'},
                                       'CONSULTANT': {'primary_interaction_paradigm': 'EXTERNAL_NEGOTIATION'}},
                 'business_topology': {'links': [{'source': 'GOV_AGENCY',
                                                  'target': 'OP_MOBILE',
                                                  'status': 'NEGOTIATING',
                                                  'value': 500,
                                                  'desc': '政务云基础通信服务'},
                                                 {'source': 'GOV_AGENCY',
                                                  'target': 'OP_TELECOM',
                                                  'status': 'NEGOTIATING',
                                                  'value': 550,
                                                  'desc': '政务云专线备份'},
                                                 {'source': 'FIN_BANK',
                                                  'target': 'OP_UNICOM',
                                                  'status': 'NEGOTIATING',
                                                  'value': 600,
                                                  'desc': '银行核心交易网络'},
                                                 {'source': 'FIN_BANK',
                                                  'target': 'OP_MOBILE',
                                                  'status': 'NEGOTIATING',
                                                  'value': 580,
                                                  'desc': '银行灾备网络'},
                                                 {'source': 'EDU_UNIV',
                                                  'target': 'OP_TELECOM',
                                                  'status': 'NEGOTIATING',
                                                  'value': 300,
                                                  'desc': '高校科研专网'},
                                                 {'source': 'MED_HOSP',
                                                  'target': 'OP_MOBILE',
                                                  'status': 'NEGOTIATING',
                                                  'value': 400,
                                                  'desc': '远程医疗5G专网'},
                                                 {'source': 'IND_FACTORY',
                                                  'target': 'OP_UNICOM',
                                                  'status': 'NEGOTIATING',
                                                  'value': 450,
                                                  'desc': '工业互联网5G专网'},
                                                 {'source': 'IND_FACTORY',
                                                  'target': 'OP_MOBILE',
                                                  'status': 'NEGOTIATING',
                                                  'value': 420,
                                                  'desc': '工厂备选方案'}]}},
 'scene_tasks': [{'task_id': 'scene-complete',
                  'name': '完成剧本级验收',
                  'goal': '完成《电信运营商招投标竞争与机构合作仿真》剧本目标，并满足全部 Agent 核心目标与全局规则。',
                  'input': {'legacy_scene': 'telecom_bidding_test'},
                  'depends_on': ['gov_agency-primary',
                                 'fin_bank-primary',
                                 'edu_univ-primary',
                                 'med_hosp-primary',
                                 'ind_factory-primary',
                                 'op_mobile-primary',
                                 'op_unicom-primary',
                                 'op_telecom-primary',
                                 'regulator-primary',
                                 'consultant-primary']}]}
